<?php

/**
 * @file
 * Implement UUID/Entity hooks for integrating with deploy and other modules.
 */

/**
 * Implements hook_entity_info_alter().
 */
function captcha_uuid_entity_info_alter(&$entity_info) {
  // Set the properties bellow for bean entity so UUIDs get created on sync.
  $entity_info['captcha_point']['uuid'] = TRUE;
  $entity_info['captcha_point']['entity keys']['uuid'] = 'uuid';
}

/**
 * Implements hook_entity_uuid_load().
 */
function captcha_uuid_entity_uuid_load(&$entities, $entity_type) {
  if ($entity_type == 'captcha_point') {
    entity_property_id_to_uuid($entities, 'captcha_point', 'id');
  }
}

/**
 * Implements hook_entity_uuid_presave().
 */
function captcha_uuid_entity_uuid_presave(&$entity, $entity_type) {
  if ($entity_type == 'captcha_point') {
    entity_property_uuid_to_id($entity, 'captcha_point', 'id');
  }
}
